# Copyright (C) 2011-2014 The CyanogenMod project
# Copyright (C) 2015 The Erikcas project :-P
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/eagle/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/eagle/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/sony/eagle/proprietary/lib/hw/sensors.msm8226.so:system/lib/hw/sensors.msm8226.so \
    vendor/sony/eagle/proprietary/lib/libyasalgo.so:system/lib/libyasalgo.so \
    vendor/sony/eagle/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so
